import Head from "next/head";
import Image from "next/image";
import Nav from "../components/nav";
import Faith from "../sections/faith";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div >
      <Head>
        <title>The Future is Yours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Nav />
      <main className={styles.main}>
        <Faith />
      </main>

      <footer className={styles.footer}>
        <div>
          made with love by
          <a
            href="https://liftedcreative.studio"
            target="_blank"
            rel="noopener noreferrer"
          >
            {" "}
            lifted
          </a>
        </div>
      </footer>
    </div>
  );
}
