import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Future is Yours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          The Future<a href="#none"> is Yours!</a>
        </h1>

        <div className={styles.grid}></div>
      </main>

      <footer className={styles.footer}>
        <div>
          made with love by
          <a
            href="https://liftedcreative.studio"
            target="_blank"
            rel="noopener noreferrer"
          >
            {" "}
            lifted
          </a>
        </div>
      </footer>
    </div>
  );
}
